# This file is auto-generated by scripts/transpile_miio.py
# Do not edit manually. Edit the build script instead.

MIIO_SPECS = {
    "dmaker.fan.p5": {
        "miio_commands": [{'method': 'get_prop', 'params': ['power', 'mode', 'speed', 'roll_enable', 'roll_angle', 'time_off', 'light', 'beep_sound', 'child_lock'], 'values': True}],
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": "s_power",
            },
            "prop.2.2": {
                "prop": "roll_enable",
                "setter": "s_roll",
            },
            "prop.2.3": {
                "prop": "mode",
                "setter": "s_mode",
                "dict": {'nature': 0, 'normal': 1},
            },
            "prop.2.4": {
                "prop": "speed",
                "setter": "s_speed",
                "template": lambda value, props, max_val: round(value/25),
                "set_template": lambda value, props, max_val: [round(value*25)],
            },
            "prop.2.5": {
                "prop": "roll_angle",
                "setter": "s_angle",
                "set_template": lambda value, props, max_val: [int(value)],
            },
            "prop.2.6": {
                "prop": "speed",
                "setter": "s_speed",
                "set_template": lambda value, props, max_val: [int(value)],
            },
            "prop.3.1": {
                "prop": "child_lock",
                "setter": "s_lock",
            },
            "prop.4.1": {
                "prop": "light",
                "setter": "s_light",
            },
            "prop.5.1": {
                "prop": "beep_sound",
                "setter": "s_sound",
            },
            "prop.6.1": {
                "prop": "time_off",
                "setter": "s_t_off",
                "set_template": lambda value, props, max_val: [int(value)],
            },
            "prop.200.201": {
                "prop": "time_off",
                "setter": "s_t_off",
                "set_template": lambda value, props, max_val: [int(value)],
            },
        }
    },
    "yeelink.light.bslamp1": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
                "set_template": lambda value, props, max_val: ["on" if value else "off", "smooth", 500],
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
            },
            "prop.2.3": {
                "prop": "rgb",
                "setter": True,
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.2.4": {
                "prop": "ct",
                "setter": "set_ct_abx",
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.2.5": {
                "prop": "color_mode",
            },
            "prop.2.101": {
                "prop": "nl_br",
                "setter": True,
            },
            "prop.2.102": {
                "prop": "delayoff",
                "setter": "set_scene",
                "set_template": lambda value, props, max_val: ["auto_delay_off", int(props.get("bright", 100)), value],
            },
            "prop.2.6": {
                "prop": "sat",
            },
        }
    },
    "yeelink.light.bslamp2": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
                "set_template": lambda value, props, max_val: ["on" if value else "off", "smooth", 500],
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
            },
            "prop.2.3": {
                "prop": "ct",
                "setter": "set_ct_abx",
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.2.4": {
                "prop": "rgb",
                "setter": True,
            },
            "prop.2.5": {
                "prop": "color_mode",
            },
            "prop.2.101": {
                "prop": "nl_br",
                "setter": True,
            },
            "prop.2.102": {
                "prop": "delayoff",
                "setter": "set_scene",
                "set_template": lambda value, props, max_val: ["auto_delay_off", int(props.get("bright", 100)), value],
            },
            "prop.2.6": {
                "prop": "sat",
            },
        }
    },
    "yeelink.light.bslamp3": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
                "set_template": lambda value, props, max_val: ["on" if value else "off", "smooth", 500],
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
            },
            "prop.2.3": {
                "prop": "ct",
                "setter": "set_ct_abx",
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.2.4": {
                "prop": "color_mode",
                "setter": True,
            },
            "prop.2.5": {
                "prop": "rgb",
                "setter": True,
            },
            "prop.2.101": {
                "prop": "nl_br",
                "setter": True,
            },
            "prop.2.102": {
                "prop": "delayoff",
                "setter": "set_scene",
                "set_template": lambda value, props, max_val: ["auto_delay_off", int(props.get("bright", 100)), value],
            },
        }
    },
    "yeelink.light.lamp1": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
            },
            "prop.2.3": {
                "prop": "ct",
                "setter": "set_ct_abx",
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.2.4": {
                "prop": "color_mode",
            },
        }
    },
    "yeelink.light.lamp10": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
                "set_template": lambda value, props, max_val: ["on" if value else "off", "smooth", 500],
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
            },
            "prop.2.3": {
                "prop": "ct",
                "setter": "set_ct_abx",
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.2.4": {
                "prop": "color_mode",
                "setter": True,
            },
            "prop.2.5": {
                "prop": "rgb",
                "setter": True,
            },
            "prop.2.101": {
                "prop": "nl_br",
                "setter": True,
            },
            "prop.2.102": {
                "prop": "delayoff",
                "setter": "set_scene",
                "set_template": lambda value, props, max_val: ["auto_delay_off", int(props.get("bright", 100)), value],
            },
        }
    },
    "yeelink.light.lamp15": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
            },
            "prop.2.3": {
                "prop": "ct",
                "setter": "set_ct_abx",
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.2.5": {
                "prop": "color_mode",
            },
            "prop.3.6": {
                "prop": "bg_power",
                "setter": "bg_set_power",
                "format": "onoff",
            },
            "prop.200.201": {
                "prop": "bg_power",
                "setter": "bg_set_power",
                "format": "onoff",
            },
            "prop.200.202": {
                "prop": "bg_bright",
                "setter": "bg_set_bright",
            },
            "prop.200.203": {
                "prop": "bg_ct",
                "setter": "bg_set_ct_abx",
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.200.204": {
                "prop": "bg_rgb",
                "setter": "bg_set_rgb",
            },
        }
    },
    "yeelink.light.lamp2": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
                "set_template": lambda value, props, max_val: ["on" if value else "off", "smooth", 500],
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
            },
            "prop.2.3": {
                "prop": "ct",
                "setter": "set_ct_abx",
                "template": lambda value, props, max_val: 2 if int(value) else 1,
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.2.102": {
                "prop": "delayoff",
                "setter": "set_scene",
                "set_template": lambda value, props, max_val: ["auto_delay_off", int(props.get("bright", 100)), value],
            },
        }
    },
    "yeelink.light.lamp3": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
            },
        }
    },
    "yeelink.light.lamp4": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
                "template": lambda value, props, max_val: int(props.get("nl_br", 0)) if int(props.get("nl_br", 0)) else value,
            },
            "prop.2.3": {
                "prop": "ct",
                "setter": "set_ct_abx",
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.2.102": {
                "prop": "delayoff",
                "setter": "set_scene",
                "set_template": lambda value, props, max_val: ["auto_delay_off", int(props.get("bright", 100)), value],
            },
        }
    },
    "yeelink.light.lamp5": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
            },
        }
    },
    "yeelink.light.lamp7": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
                "set_template": lambda value, props, max_val: ["on" if value else "off", "smooth", 500],
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
            },
            "prop.2.3": {
                "prop": "ct",
                "setter": "set_ct_abx",
                "template": lambda value, props, max_val: 2 if int(value) else 1,
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.2.102": {
                "prop": "delayoff",
                "setter": "set_scene",
                "set_template": lambda value, props, max_val: ["auto_delay_off", int(props.get("bright", 100)), value],
            },
        }
    },
    "yeelink.light.lamp9": {
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "bright",
                "setter": True,
                "template": lambda value, props, max_val: int(props.get("nl_br", 0)) if int(props.get("nl_br", 0)) else value,
            },
            "prop.2.3": {
                "prop": "ct",
                "setter": "set_ct_abx",
                "set_template": lambda value, props, max_val: [value, "smooth", 500],
            },
            "prop.2.102": {
                "prop": "delayoff",
                "setter": "set_scene",
                "set_template": lambda value, props, max_val: ["auto_delay_off", int(props.get("bright", 100)), value],
            },
            "prop.2.4": {
                "prop": "active_mode",
                "setter": "set_ps",
                "template": lambda value, props, max_val: 2 if int(value) else 1,
                "set_template": lambda value, props, max_val: ["nightlight", "on" if value == 2 else "off"],
            },
        }
    },
    "zhimi.fan.sa1": {
        "chunk_properties": 1,
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "speed_level",
                "setter": True,
                "template": lambda value, props, max_val: (int(props.get("natural_level", value) or 0) if max_val == 100 else (1 if int(props.get("natural_level", value) or 0) <= 25 else (2 if int(props.get("natural_level", value) or 0) <= 50 else (3 if int(props.get("natural_level", value) or 0) <= 75 else 4)))),
                "set_template": lambda value, props, max_val: {"method": "set_natural_level" if int(props.get("natural_level", 0)) else "set_speed_level", "params": [int(value or 0) * (1 if max_val == 100 else 25)]},
            },
            "prop.2.3": {
                "prop": "angle_enable",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.4": {
                "prop": "angle",
                "setter": True,
            },
            "prop.2.5": {
                "prop": "natural_level",
                "setter": True,
                "template": lambda value, props, max_val: 1 if int(value or 0) > 0 else 2,
                "set_template": lambda value, props, max_val: [int(value or 0) * 25],
            },
            "prop.3.1": {
                "prop": "child_lock",
                "setter": True,
                "format": "onoff",
            },
        }
    },
    "zhimi.fan.v2": {
        "chunk_properties": 15,
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "speed_level",
                "setter": True,
                "template": lambda value, props, max_val: (int(props.get("natural_level", value) or 0) if max_val == 100 else (1 if int(props.get("natural_level", value) or 0) <= 25 else (2 if int(props.get("natural_level", value) or 0) <= 50 else (3 if int(props.get("natural_level", value) or 0) <= 75 else 4)))),
                "set_template": lambda value, props, max_val: {"method": "set_natural_level" if int(props.get("natural_level", 0)) else "set_speed_level", "params": [int(value or 0) * (1 if max_val == 100 else 25)]},
            },
            "prop.2.3": {
                "prop": "angle_enable",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.4": {
                "prop": "angle",
                "setter": True,
            },
            "prop.2.5": {
                "prop": "natural_level",
                "setter": True,
                "template": lambda value, props, max_val: 1 if int(value or 0) > 0 else 0,
                "set_template": lambda value, props, max_val: [int(value or 0) * 25],
            },
            "prop.3.1": {
                "prop": "child_lock",
                "setter": True,
                "format": "onoff",
            },
            "prop.4.1": {
                "prop": "battery",
            },
            "prop.4.2": {
                "prop": "bat_charge",
                "template": lambda value, props, max_val: 2 if value == "complete" else 1,
            },
        }
    },
    "zhimi.fan.v3": {
        "chunk_properties": 15,
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "speed_level",
                "setter": True,
                "template": lambda value, props, max_val: (int(props.get("natural_level", value) or 0) if max_val == 100 else (1 if int(props.get("natural_level", value) or 0) <= 25 else (2 if int(props.get("natural_level", value) or 0) <= 50 else (3 if int(props.get("natural_level", value) or 0) <= 75 else 4)))),
                "set_template": lambda value, props, max_val: {"method": "set_natural_level" if int(props.get("natural_level", 0)) else "set_speed_level", "params": [int(value or 0) * (1 if max_val == 100 else 25)]},
            },
            "prop.2.3": {
                "prop": "angle_enable",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.4": {
                "prop": "angle",
                "setter": True,
            },
            "prop.2.5": {
                "prop": "natural_level",
                "setter": True,
                "template": lambda value, props, max_val: 1 if int(value or 0) > 0 else 0,
                "set_template": lambda value, props, max_val: [int(value or 0) * 25],
            },
            "prop.3.1": {
                "prop": "child_lock",
                "setter": True,
                "format": "onoff",
            },
            "prop.4.1": {
                "prop": "battery",
            },
            "prop.4.2": {
                "prop": "bat_charge",
                "template": lambda value, props, max_val: 2 if value == "complete" else 1,
            },
        }
    },
    "zhimi.fan.za1": {
        "chunk_properties": 1,
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "speed_level",
                "setter": True,
                "template": lambda value, props, max_val: (int(props.get("natural_level", value) or 0) if max_val == 100 else (1 if int(props.get("natural_level", value) or 0) <= 25 else (2 if int(props.get("natural_level", value) or 0) <= 50 else (3 if int(props.get("natural_level", value) or 0) <= 75 else 4)))),
                "set_template": lambda value, props, max_val: {"method": "set_natural_level" if int(props.get("natural_level", 0)) else "set_speed_level", "params": [int(value or 0) * (1 if max_val == 100 else 25)]},
            },
            "prop.2.3": {
                "prop": "angle_enable",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.4": {
                "prop": "angle",
                "setter": True,
            },
            "prop.2.5": {
                "prop": "natural_level",
                "setter": True,
                "template": lambda value, props, max_val: 1 if int(value or 0) > 0 else 2,
                "set_template": lambda value, props, max_val: [int(value or 0) * 25],
            },
            "prop.3.1": {
                "prop": "child_lock",
                "setter": True,
                "format": "onoff",
            },
        }
    },
    "zhimi.fan.za3": {
        "chunk_properties": 1,
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "speed_level",
                "setter": True,
                "template": lambda value, props, max_val: (int(props.get("natural_level", value) or 0) if max_val == 100 else (1 if int(props.get("natural_level", value) or 0) <= 25 else (2 if int(props.get("natural_level", value) or 0) <= 50 else (3 if int(props.get("natural_level", value) or 0) <= 75 else 4)))),
                "set_template": lambda value, props, max_val: {"method": "set_natural_level" if int(props.get("natural_level", 0)) else "set_speed_level", "params": [int(value or 0) * (1 if max_val == 100 else 25)]},
            },
            "prop.2.3": {
                "prop": "angle_enable",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.4": {
                "prop": "angle",
                "setter": True,
            },
            "prop.2.5": {
                "prop": "natural_level",
                "setter": True,
                "template": lambda value, props, max_val: 1 if int(value or 0) > 0 else 0,
                "set_template": lambda value, props, max_val: [int(value or 0) * 25],
            },
            "prop.3.1": {
                "prop": "child_lock",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.6": {
                "prop": "speed_level",
                "setter": True,
                "template": lambda value, props, max_val: int(props.get("natural_level", value) or 0),
                "set_template": lambda value, props, max_val: {"method": "set_natural_level" if int(props.get("natural_level", 0)) else "set_speed_level", "params": [int(value or 0)]},
            },
            "prop.4.1": {
                "prop": "buzzer",
                "setter": True,
                "template": lambda value, props, max_val: int(value or 0) > 0,
                "set_template": lambda value, props, max_val: [1 if value else 0],
            },
            "prop.5.1": {
                "prop": "led_b",
                "setter": True,
                "template": lambda value, props, max_val: int(value or 0) > 0,
                "set_template": lambda value, props, max_val: [1 if value else 0],
            },
        }
    },
    "zhimi.fan.za4": {
        "chunk_properties": 1,
        "miio_specs": {
            "prop.2.1": {
                "prop": "power",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.2": {
                "prop": "speed_level",
                "setter": True,
                "template": lambda value, props, max_val: (int(props.get("natural_level", value) or 0) if max_val == 100 else (1 if int(props.get("natural_level", value) or 0) <= 25 else (2 if int(props.get("natural_level", value) or 0) <= 50 else (3 if int(props.get("natural_level", value) or 0) <= 75 else 4)))),
                "set_template": lambda value, props, max_val: {"method": "set_natural_level" if int(props.get("natural_level", 0)) else "set_speed_level", "params": [int(value or 0) * (1 if max_val == 100 else 25)]},
            },
            "prop.2.3": {
                "prop": "angle_enable",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.4": {
                "prop": "angle",
                "setter": True,
            },
            "prop.2.5": {
                "prop": "natural_level",
                "setter": True,
                "template": lambda value, props, max_val: 1 if int(value or 0) > 0 else 0,
                "set_template": lambda value, props, max_val: [int(value or 0) * 25],
            },
            "prop.3.1": {
                "prop": "child_lock",
                "setter": True,
                "format": "onoff",
            },
            "prop.2.6": {
                "prop": "speed_level",
                "setter": True,
                "template": lambda value, props, max_val: int(props.get("natural_level", value) or 0),
                "set_template": lambda value, props, max_val: {"method": "set_natural_level" if int(props.get("natural_level", 0)) else "set_speed_level", "params": [int(value or 0)]},
            },
            "prop.4.1": {
                "prop": "buzzer",
                "setter": True,
                "template": lambda value, props, max_val: int(value or 0) > 0,
                "set_template": lambda value, props, max_val: [1 if value else 0],
            },
            "prop.5.1": {
                "prop": "led_b",
                "setter": True,
                "template": lambda value, props, max_val: int(value or 0) > 0,
                "set_template": lambda value, props, max_val: [1 if value else 0],
            },
        }
    },
}
